export const DataDictionary = [
    {
        idAll: 1,
        idMain: 1,
        id: 1,
        english: "afraid",
        inenglish: ["afraid", "agree", "angry", "arrive"],
        uzbek: "qo'rqqan, cho'chigan",
        inuzbek: [
            "qo'rqqan, cho'chigan",
            "fikriga qo'shilmoq, rozi bo'lmoq",
            "jahli chiqqan, badjahl",
            "yetib kelmoq, kelmoq",
        ],
    },
    {
        idAll: 2,
        idMain: 1,
        id: 2,
        english: "agree",
        inenglish: ["agree", "afraid", "angry", "arrive"],
        uzbek: "fikriga qo'shilmoq, rozi bo'lmoq",
        inuzbek: [
            "fikriga qo'shilmoq, rozi bo'lmoq",
            "qo'rqqan, cho'chigan",
            "jahli chiqqan, badjahl",
            "yetib kelmoq, kelmoq",
        ],
    },
    {
        idAll: 3,
        idMain: 1,
        id: 3,
        english: "angry",
        inenglish: ["angry", "agree", "afraid", "arrive"],
        uzbek: "jahli chiqqan, badjahl",
        inuzbek: [
            "jahli chiqqan, badjahl",
            "fikriga qo'shilmoq, rozi bo'lmoq",
            "qo'rqqan, cho'chigan",
            "yetib kelmoq, kelmoq",
        ],
    },
    {
        idAll: 4,
        idMain: 1,
        id: 4,
        english: "arrive",
        inenglish: ["arrive", "angry", "agree", "afraid"],
        uzbek: "yetib kelmoq, kelmoq",
        inuzbek: [
            "yetib kelmoq, kelmoq",
            "jahli chiqqan, badjahl",
            "fikriga qo'shilmoq, rozi bo'lmoq",
            "qo'rqqan, cho'chigan",
        ],
    },
    {
        idAll: 5,
        idMain: 1,
        id: 5,
        english: "attack",
        inenglish: ["attack", "bottom", "clever", "cruel"],
        uzbek: "hujum qilmoq",
        inuzbek: [
            "hujum qilmoq",
            "tag, pastki qism",
            "aqilli, ziyrak",
            "shafqatsiz, berahm",
        ],
    },
    {
        idAll: 6,
        idMain: 1,
        id: 6,
        english: "bottom",
        inenglish: ["bottom", "attack", "clever", "cruel"],
        uzbek: "tag, pastki qism",
        inuzbek: [
            "tag, pastki qism",
            "hujum qilmoq",
            "aqilli, ziyrak",
            "shafqatsiz, berahm",
        ],
    },
    {
        idAll: 7,
        idMain: 1,
        id: 7,
        english: "clever",
        inenglish: ["clever", "attack", "bottom", "cruel"],
        uzbek: "aqilli, ziyrak",
        inuzbek: [
            "aqilli, ziyrak",
            "hujum qilmoq",
            "tag, pastki qism",
            "shafqatsiz, berahm",
        ],
    },
    {
        idAll: 8,
        idMain: 1,
        id: 8,
        english: "cruel",
        inenglish: ["cruel", "attack", "bottom", "clever"],
        uzbek: "shafqatsiz, berahm",
        inuzbek: [
            "shafqatsiz, berahm",
            "hujum qilmoq",
            "tag, pastki qism",
            "aqilli, ziyrak",
        ],
    },
    {
        idAll: 9,
        idMain: 1,
        id: 9,
        english: "finally",
        inenglish: ["finally", "hide", "hunt", "lot"],
        uzbek: "axiyri, vanihoyat",
        inuzbek: [
            "axiyri, vanihoyat",
            "yashirinmoq, bekinmoq",
            "ov qilmoq, ovlamoq",
            "juda ko'p",
        ],
    },
    {
        idAll: 10,
        idMain: 1,
        id: 10,
        english: "hide",
        inenglish: ["hide", "finally", "hunt", "lot"],
        uzbek: "yashirinmoq, bekinmoq",
        inuzbek: [
            "yashirinmoq, bekinmoq",
            "axiyri, vanihoyat",
            "ov qilmoq, ovlamoq",
            "juda ko'p",
        ],
    },
    {
        idAll: 11,
        idMain: 1,
        id: 11,
        english: "hunt",
        inenglish: ["hunt", "finally", "hide", "lot"],
        uzbek: "ov qilmoq, ovlamoq",
        inuzbek: [
            "ov qilmoq, ovlamoq",
            "axiyri, vanihoyat",
            "yashirinmoq, bekinmoq",
            "juda ko'p",
        ],
    },
    {
        idAll: 12,
        idMain: 1,
        id: 12,
        english: "lot",
        inenglish: ["lot", "finally", "hide", "hunt"],
        uzbek: "juda ko'p",
        inuzbek: [
            "juda ko'p",
            "axiyri, vanihoyat",
            "yashirinmoq, bekinmoq",
            "ov qilmoq, ovlamoq",
        ],
    },
    {
        idAll: 13,
        idMain: 1,
        id: 13,
        english: "middle",
        inenglish: ["middle", "moment", "pleased", "promise"],
        uzbek: "o'rta",
        inuzbek: [
            "o'rta",
            "daqiqa, on, zum",
            "hursand, mamnun",
            "va'da bermoq",
        ],
    },
    {
        idAll: 14,
        idMain: 1,
        id: 14,
        english: "moment",
        inenglish: ["moment", "middle", "pleased", "promise"],
        uzbek: "daqiqa, on, zum",
        inuzbek: [
            "daqiqa, on, zum",
            "o'rta",
            "hursand, mamnun",
            "va'da bermoq",
        ],
    },
    {
        idAll: 15,
        idMain: 1,
        id: 15,
        english: "pleased",
        inenglish: ["pleased", "middle", "moment", "promise"],
        uzbek: "hursand, mamnun",
        inuzbek: [
            "hursand, mamnun",
            "o'rta",
            "daqiqa, on, zum",
            "va'da bermoq",
        ],
    },
    {
        idAll: 16,
        idMain: 1,
        id: 16,
        english: "promise",
        inenglish: ["promise", "middle", "moment", "pleased"],
        uzbek: "va'da bermoq",
        inuzbek: [
            "va'da bermoq",
            "o'rta",
            "daqiqa, on, zum",
            "hursand, mamnun",
        ],
    },
    {
        idAll: 17,
        idMain: 1,
        id: 17,
        english: "reply",
        inenglish: ["reply", "safe", "trick", "well"],
        uzbek: "javob bermoq",
        inuzbek: [
            "javob bermoq",
            "xavfsiz, bexatar",
            "xiyla, nayrang",
            "yaxshi",
        ],
    },
    {
        idAll: 18,
        idMain: 1,
        id: 18,
        english: "safe",
        inenglish: ["safe", "reply", "trick", "well"],
        uzbek: "xavfsiz, bexatar",
        inuzbek: [
            "xavfsiz, bexatar",
            "javob bermoq",
            "xiyla, nayrang",
            "yaxshi",
        ],
    },
    {
        idAll: 19,
        idMain: 1,
        id: 19,
        english: "trick",
        inenglish: ["trick", "reply", "safe", "well"],
        uzbek: "xiyla, nayrang",
        inuzbek: [
            "xiyla, nayrang",
            "javob bermoq",
            "xavfsiz, bexatar",
            "yaxshi",
        ],
    },
    {
        idAll: 20,
        idMain: 1,
        id: 20,
        english: "well",
        inenglish: ["well", "reply", "safe", "trick"],
        uzbek: "yaxshi",
        inuzbek: [
            "yaxshi",
            "javob bermoq",
            "xavfsiz, bexatar",
            "xiyla, nayrang",
        ],
    },
    // UNIT 2
    {
        idAll: 21,
        idMain: 2,
        id: 1,
        english: "adventure",
        inenglish: ["adventure", "approach", "carefully", "chemical"],
        uzbek: "sarguzasht",
        inuzbek: [
            "sarguzasht",
            "yaqinlashmoq, yaqin kelmoq",
            "e'tibor bilan, ehtiyotkorlik bilan",
            "kimyoviy modda",
        ],
    },
    {
        idAll: 22,
        idMain: 2,
        id: 2,
        english: "approach",
        inenglish: ["approach", "adventure", "carefully", "chemical"],
        uzbek: "yaqinlashmoq, yaqin kelmoq",
        inuzbek: [
            "yaqinlashmoq, yaqin kelmoq",
            "sarguzasht",
            "e'tibor bilan, ehtiyotkorlik bilan",
            "kimyoviy modda",
        ],
    },
    {
        idAll: 23,
        idMain: 2,
        id: 3,
        english: "carefully",
        inenglish: ["carefully", "adventure", "approach", "chemical"],
        uzbek: "e'tibor bilan, ehtiyotkorlik bilan",
        inuzbek: [
            "e'tibor bilan, ehtiyotkorlik bilan",
            "sarguzasht",
            "yaqinlashmoq, yaqin kelmoq",
            "kimyoviy modda",
        ],
    },
    {
        idAll: 24,
        idMain: 2,
        id: 4,
        english: "chemical",
        inenglish: ["chemical", "adventure", "approach", "carefully"],
        uzbek: "kimyoviy modda",
        inuzbek: [
            "kimyoviy modda",
            "sarguzasht",
            "yaqinlashmoq, yaqin kelmoq",
            "e'tibor bilan, ehtiyotkorlik bilan",
        ],
    },
    {
        idAll: 25,
        idMain: 2,
        id: 5,
        english: "create",
        inenglish: ["create", "evil", "experiment", "kill"],
        uzbek: "yaratmoq",
        inuzbek: ["yaratmoq", "yomon, yovuz", "tajriba, sinov", "o'ldirmoq"],
    },
    {
        idAll: 26,
        idMain: 2,
        id: 6,
        english: "evil",
        inenglish: ["evil", "create", "experiment", "kill"],
        uzbek: "yomon, yovuz",
        inuzbek: ["yomon, yovuz", "yaratmoq", "tajriba, sinov", "o'ldirmoq"],
    },
    {
        idAll: 27,
        idMain: 2,
        id: 7,
        english: "experiment",
        inenglish: ["experiment", "create", "evil", "kill"],
        uzbek: "tajriba, sinov",
        inuzbek: ["tajriba, sinov", "yaratmoq", "yomon, yovuz", "o'ldirmoq"],
    },
    {
        idAll: 28,
        idMain: 2,
        id: 8,
        english: "kill",
        inenglish: ["kill", "create", "evil", "experiment"],
        uzbek: "o'ldirmoq",
        inuzbek: ["o'ldirmoq", "yaratmoq", "yomon, yovuz", "tajriba, sinov"],
    },
    {
        idAll: 29,
        idMain: 2,
        id: 9,
        english: "laboratory",
        inenglish: ["laboratory", "laugh", "loud", "nervous"],
        uzbek: "laboratoriya",
        inuzbek: [
            "laboratoriya",
            "kulgi",
            "shovqinli, baland",
            "xavotirlangan, xavotirga tushgan",
        ],
    },
    {
        idAll: 30,
        idMain: 2,
        id: 10,
        english: "laugh",
        inenglish: ["laugh", "laboratory", "loud", "nervous"],
        uzbek: "kulgi",
        inuzbek: [
            "kulgi",
            "laboratoriya",
            "shovqinli, baland",
            "xavotirlangan, xavotirga tushgan",
        ],
    },
    {
        idAll: 31,
        idMain: 2,
        id: 11,
        english: "loud",
        inenglish: ["loud", "laboratory", "laugh", "nervous"],
        uzbek: "shovqinli, baland",
        inuzbek: [
            "shovqinli, baland",
            "laboratoriya",
            "kulgi",
            "xavotirlangan, xavotirga tushgan",
        ],
    },
    {
        idAll: 32,
        idMain: 2,
        id: 12,
        english: "nervous",
        inenglish: ["nervous", "laboratory", "laugh", "loud"],
        uzbek: "xavotirlangan, xavotirga tushgan",
        inuzbek: [
            "xavotirlangan, xavotirga tushgan",
            "laboratoriya",
            "kulgi",
            "shovqinli, baland",
        ],
    },
    {
        idAll: 33,
        idMain: 2,
        id: 13,
        english: "noise",
        inenglish: ["noise", "project", "scare", "secret"],
        uzbek: "shovqin, yoqimsiz ovoz",
        inuzbek: [
            "shovqin, yoqimsiz ovoz",
            "loyiha, mahsus topshiriq",
            "qo'rqitmoq' daxshatga solmoq",
            "sir",
        ],
    },
    {
        idAll: 34,
        idMain: 2,
        id: 14,
        english: "project",
        inenglish: ["project", "noise", "scare", "secret"],
        uzbek: "loyiha, mahsus topshiriq",
        inuzbek: [
            "loyiha, mahsus topshiriq",
            "shovqin, yoqimsiz ovoz",
            "qo'rqitmoq' daxshatga solmoq",
            "sir",
        ],
    },
    {
        idAll: 35,
        idMain: 2,
        id: 15,
        english: "scare",
        inenglish: ["scare", "noise", "project", "secret"],
        uzbek: "qo'rqitmoq' daxshatga solmoq",
        inuzbek: [
            "qo'rqitmoq' daxshatga solmoq",
            "shovqin, yoqimsiz ovoz",
            "loyiha, mahsus topshiriq",
            "sir",
        ],
    },
    {
        idAll: 36,
        idMain: 2,
        id: 16,
        english: "secret",
        inenglish: ["secret", "noise", "project", "scare"],
        uzbek: "sir",
        inuzbek: [
            "sir",
            "shovqin, yoqimsiz ovoz",
            "loyiha, mahsus topshiriq",
            "qo'rqitmoq' daxshatga solmoq",
        ],
    },
    {
        idAll: 37,
        idMain: 2,
        id: 17,
        english: "shout",
        inenglish: ["shout", "smell", "terrible", "worse"],
        uzbek: "baqirmoq, qichqirmoq",
        inuzbek: [
            "baqirmoq, qichqirmoq",
            "hidlanmoq, hidlab ko'rmoq",
            "juda yomon",
            "yomonroq",
        ],
    },
    {
        idAll: 38,
        idMain: 2,
        id: 18,
        english: "smell",
        inenglish: ["smell", "shout", "terrible", "worse"],
        uzbek: "hidlanmoq, hidlab ko'rmoq",
        inuzbek: [
            "hidlanmoq, hidlab ko'rmoq",
            "baqirmoq, qichqirmoq",
            "juda yomon",
            "yomonroq",
        ],
    },
    {
        idAll: 39,
        idMain: 2,
        id: 19,
        english: "terrible",
        inenglish: ["terrible", "shout", "smell", "worse"],
        uzbek: "juda yomon",
        inuzbek: [
            "juda yomon",
            "baqirmoq, qichqirmoq",
            "hidlanmoq, hidlab ko'rmoq",
            "yomonroq",
        ],
    },
    {
        idAll: 40,
        idMain: 2,
        id: 20,
        english: "worse",
        inenglish: ["worse", "shout", "smell", "terrible"],
        uzbek: "yomonroq",
        inuzbek: [
            "yomonroq",
            "baqirmoq, qichqirmoq",
            "hidlanmoq, hidlab ko'rmoq",
            "juda yomon",
        ],
    },
    //Unit 3
    {
        idAll: 41,
        idMain: 3,
        id: 1,
        english: "alien",
        inenglish: [
            "alien", 
            "among", 
            "chart", 
            "cloud"],
        uzbek: "o'zga sayyoralik",
        inuzbek: [
            "o'zga sayyoralik",
            "orasida, ichida",
            "diagramma",
            "bulut",
        ],
    },
    {
        idAll: 42,
        idMain: 3,
        id: 2,
        english: "among",
        inenglish: [
            "among", 
            "alien", 
            "chart", 
            "cloud"],
        uzbek: "orasida, ichida",
        inuzbek: [
            "orasida, ichida",
            "o'zga sayyoralik",
            "diagramma",
            "bulut",
        ],
    },
    {
        idAll: 43,
        idMain: 3,
        id: 3,
        english: "chart",
        inenglish: [
            "chart", 
            "alien", 
            "among", 
            "cloud"],
        uzbek: "diagramma",
        inuzbek: [
            "diagramma",
            "o'zga sayyoralik",
            "orasida, ichida",
            "bulut",
        ],
    },
    {
        idAll: 44,
        idMain: 3,
        id: 4,
        english: "cloud",
        inenglish: [
            "cloud",
            "alien", 
            "among", 
            "chart", 
        ],
        uzbek: "bulut",
        inuzbek: [
            "bulut",
            "o'zga sayyoralik",
            "orasida, ichida",
            "diagramma",
        ],
    },
    {
        idAll: 45,
        idMain: 3,
        id: 5,
        english: "comprehend",
        inenglish: [
            "comprehend", 
            "describe", 
            "ever", 
            "fail"],
        uzbek: "tushunmoq, anglamoq",
        inuzbek: [
            "tushunmoq, anglamoq",
            "tasvirlamoq",
            "qachon bo'lmasin; ilgari",
            "muvaffaqiyatsizlikka uchramoq",
        ],
    },
    {
        idAll: 46,
        idMain: 3,
        id: 6,
        english: "describe",
        inenglish: [
            "describe", 
            "comprehend", 
            "ever", 
            "fail"],
        uzbek: "tasvirlamoq",
        inuzbek: [
            "tasvirlamoq",
            "tushunmoq, anglamoq",
            "qachon bo'lmasin; ilgari",
            "muvaffaqiyatsizlikka uchramoq",
        ],
    },
    {
        idAll: 47,
        idMain: 3,
        id: 7,
        english: "ever",
        inenglish: [
            "ever", 
            "comprehend", 
            "describe", 
            "fail"],
        uzbek: "qachon bo'lmasin; ilgari",
        inuzbek: [
            "qachon bo'lmasin; ilgari",
            "tushunmoq, anglamoq",
            "tasvirlamoq",
            "muvaffaqiyatsizlikka uchramoq",
        ],
    },
    {
        idAll: 48,
        idMain: 3,
        id: 8,
        english: "fail",
        inenglish: [
            "fail",
            "comprehend", 
            "describe", 
            "ever", 
        ],
        uzbek: "muvaffaqiyatsizlikka uchramoq",
        inuzbek: [
            "muvaffaqiyatsizlikka uchramoq",
            "tushunmoq, anglamoq",
            "tasvirlamoq",
            "qachon bo'lmasin; ilgari",
        ],
    },
    {
        idAll: 49,
        idMain: 3,
        id: 9,
        english: "friendly",
        inenglish: [
            "friendly", 
            "grade", 
            "instead", 
            "library"],
        uzbek: "mehribon, g'amxo'r, do'stona",
        inuzbek: [
            "mehribon, g'amxo'r, do'stona",
            "baho",
            "o'rniga",
            "kutubxona",
        ],
    },
    {
        idAll: 50,
        idMain: 3,
        id: 10,
        english: "grade",
        inenglish: [
            "grade", 
            "friendly", 
            "instead", 
            "library"],
        uzbek: "baho",
        inuzbek: [
            "baho",
            "mehribon, g'amxo'r, do'stona",
            "o'rniga",
            "kutubxona",
        ],
    },
    {
        idAll: 51,
        idMain: 3,
        id: 11,
        english: "instead",
        inenglish: [
            "instead", 
            "friendly", 
            "grade", 
            "library"],
        uzbek: "rniga",
        inuzbek: [
            "o'rniga",
            "mehribon, g'amxo'r, do'stona",
            "baho",
            "kutubxona",
        ],
    },
    {
        idAll: 52,
        idMain: 3,
        id: 12,
        english: "library",
        inenglish: [
            "library",
            "friendly", 
            "grade", 
            "instead", 
        ],
        uzbek: "kutubxona",
        inuzbek: [
            "kutubxona",
            "mehribon, g'amxo'r, do'stona",
            "baho",
            "o'rniga",
        ],
    },

    {
        idAll: 53,
        idMain: 3,
        id: 13,
        english: "planet",
        inenglish: [
            "planet", 
            "report", 
            "several", 
            "solve"],
        uzbek: "planeta, sayyora",
        inuzbek: [
            "planeta, sayyora",
            "hisobot; o'quvchi tabeli",
            "bir talay, bir nechta",
            "yechmoq, javob topmoq",
        ],
    },
    {
        idAll: 54,
        idMain: 3,
        id: 14,
        english: "report",
        inenglish: [
            "report", 
            "planet", 
            "several", 
            "solve"],
        uzbek: "hisobot; o'quvchi tabeli",
        inuzbek: [
            "hisobot; o'quvchi tabeli",
            "planeta, sayyora",
            "bir talay, bir nechta",
            "yechmoq, javob topmoq",
        ],
    },
    {
        idAll: 55,
        idMain: 3,
        id: 15,
        english: "several",
        inenglish: [
            "several", 
            "planet", 
            "report", 
            "solve"],
        uzbek: "bir talay, bir nechta",
        inuzbek: [
            "bir talay, bir nechta",
            "planeta, sayyora",
            "hisobot; o'quvchi tabeli",
            "yechmoq, javob topmoq",
        ],
    },
    {
        idAll: 56,
        idMain: 3,
        id: 16,
        english: "solve",
        inenglish: [
            "solve",
            "planet", 
            "report", 
            "several", 
        ],
        uzbek: "yechmoq, javob topmoq",
        inuzbek: [
            "yechmoq, javob topmoq",
            "planeta, sayyora",
            "hisobot; o'quvchi tabeli",
            "bir talay, bir nechta",
        ],
    },

    {
        idAll: 57,
        idMain: 3,
        id: 17,
        english: "suddenly",
        inenglish: [
            "suddenly", 
            "suppose", 
            "universe", 
            "view"],
        uzbek: "to'satdan, kutilmaganda, birdaniga",
        inuzbek: [
            "to'satdan, kutilmaganda, birdaniga",
            "deb o'ylamoq, taxmin qilmoq",
            "koinot",
            "qaramoq, ko'rmoq",
        ],
    },
    {
        idAll: 58,
        idMain: 3,
        id: 18,
        english: "suppose",
        inenglish: [
            "suppose", 
            "suddenly", 
            "universe", 
            "view"],
        uzbek: "deb o'ylamoq, taxmin qilmoq",
        inuzbek: [
            "deb o'ylamoq, taxmin qilmoq",
            "to'satdan, kutilmaganda, birdaniga",
            "koinot",
            "qaramoq, ko'rmoq",
        ],
    },
    {
        idAll: 59,
        idMain: 3,
        id: 19,
        english: "universe",
        inenglish: [
            "universe", 
            "suddenly", 
            "suppose", 
            "view"],
        uzbek: "koinot",
        inuzbek: [
            "koinot",
            "to'satdan, kutilmaganda, birdaniga",
            "deb o'ylamoq, taxmin qilmoq",
            "qaramoq, ko'rmoq",
        ],
    },
    {
        idAll: 60,
        idMain: 3,
        id: 20,
        english: "view",
        inenglish: [
            "view",
            "suddenly", 
            "suppose", 
            "universe", 
        ],
        uzbek: "qaramoq, ko'rmoq",
        inuzbek: [
            "qaramoq, ko'rmoq",
            "to'satdan, kutilmaganda, birdaniga",
            "deb o'ylamoq, taxmin qilmoq",
            "koinot",
        ],
    },

    //Unit 4
    {
        idAll: 61,
        idMain: 4,
        id: 1,
        english: "appropriate",
        inenglish: [
            "appropriate", 
            "avoid", 
            "behave", 
            "calm"],
        uzbek: "mos, to'g'ri, muvofiq",
        inuzbek: [
            "mos, to'g'ri, muvofiq",
            "yaqinlashmaslik, chetda turmoq",
            "o'zini tutmoq, odob saqlamoq",
            "xotirjam",
        ],
    },
    {
        idAll: 62,
        idMain: 4,
        id: 2,
        english: "avoid",
        inenglish: [
            "avoid", 
            "appropriate", 
            "behave", 
            "calm"],
        uzbek: "yaqinlashmaslik, chetda turmoq",
        inuzbek: [
            "yaqinlashmaslik, chetda turmoq",
            "mos, to'g'ri, muvofiq",
            "o'zini tutmoq, odob saqlamoq",
            "xotirjam",
        ],
    },
    {
        idAll: 63,
        idMain: 4,
        id: 3,
        english: "behave",
        inenglish: [
            "behave", 
            "appropriate", 
            "avoid", 
            "calm"],
        uzbek: "o'zini tutmoq, odob saqlamoq",
        inuzbek: [
            "o'zini tutmoq, odob saqlamoq",
            "mos, to'g'ri, muvofiq",
            "yaqinlashmaslik, chetda turmoq",
            "xotirjam",
        ],
    },
    {
        idAll: 64,
        idMain: 4,
        id: 4,
        english: "calm",
        inenglish: [
            "calm",
            "appropriate", 
            "avoid", 
            "behave", 
        ],
        uzbek: "xotirjam",
        inuzbek: [
            "xotirjam",
            "mos, to'g'ri, muvofiq",
            "yaqinlashmaslik, chetda turmoq",
            "o'zini tutmoq, odob saqlamoq",
        ],
    },

    {
        idAll: 65,
        idMain: 4,
        id: 5,
        english: "concern",
        inenglish: [
            "concern", 
            "content", 
            "expect", 
            "frequently"],
        uzbek: "tashvish, g'am",
        inuzbek: [
            "tashvish, g'am",
            "xursand, shod",
            "umid qilmoq, ishonmoq, kutmoq",
            "tez-tez",
        ],
    },
    {
        idAll: 66,
        idMain: 4,
        id: 6,
        english: "content",
        inenglish: [
            "content", 
            "concern", 
            "expect", 
            "frequently"],
        uzbek: "xursand, shod",
        inuzbek: [
            "xursand, shod",
            "tashvish, g'am",
            "umid qilmoq, ishonmoq, kutmoq",
            "tez-tez",
        ],
    },
    {
        idAll: 67,
        idMain: 4,
        id: 7,
        english: "expect",
        inenglish: [
            "expect", 
            "concern", 
            "content", 
            "frequently"],
        uzbek: "umid qilmoq, ishonmoq, kutmoq",
        inuzbek: [
            "umid qilmoq, ishonmoq, kutmoq",
            "tashvish, g'am",
            "xursand, shod",
            "tez-tez",
        ],
    },
    {
        idAll: 68,
        idMain: 4,
        id: 8,
        english: "frequently",
        inenglish: [
            "frequently",
            "concern", 
            "content", 
            "expect", 
        ],
        uzbek: "tez-tez",
        inuzbek: [
            "tez-tez",
            "tashvish, g'am",
            "xursand, shod",
            "umid qilmoq, ishonmoq, kutmoq",
        ],
    },

    {
        idAll: 69,
        idMain: 4,
        id: 9,
        english: "habit",
        inenglish: [
            "habit", 
            "instruct", 
            "issue", 
            "none"],
        uzbek: "odat",
        inuzbek: [
            "odat",
            "ta'lim bermoq; ko'rsatma bermoq",
            "masala, muammo",
            "hech qancha",
        ],
    },
    {
        idAll: 70,
        idMain: 4,
        id: 10,
        english: "instruct",
        inenglish: [
            "instruct", 
            "habit", 
            "issue", 
            "none"],
        uzbek: "ta'lim bermoq; ko'rsatma bermoq",
        inuzbek: [
            "ta'lim bermoq; ko'rsatma bermoq",
            "odat",
            "masala, muammo",
            "hech qancha",
        ],
    },
    {
        idAll: 71,
        idMain: 4,
        id: 11,
        english: "issue",
        inenglish: [
            "issue", 
            "habit", 
            "instruct", 
            "none"],
        uzbek: "masala, muammo",
        inuzbek: [
            "masala, muammo",
            "odat",
            "ta'lim bermoq; ko'rsatma bermoq",
            "hech qancha",
        ],
    },
    {
        idAll: 72,
        idMain: 4,
        id: 12,
        english: "none",
        inenglish: [
            "none",
            "habit", 
            "instruct", 
            "issue", 
        ],
        uzbek: "hech qancha",
        inuzbek: [
            "hech qancha",
            "odat",
            "ta'lim bermoq; ko'rsatma bermoq",
            "masala, muammo",
        ],
    },

    {
        idAll: 73,
        idMain: 4,
        id: 13,
        english: "patient",
        inenglish: [
            "patient", 
            "positive", 
            "punish", 
            "represent"],
        uzbek: "sabrli, toqatli",
        inuzbek: [
            "sabrli, toqatli",
            "ijobiy, porloq",
            "jazolamoq",
            "vakil bo'lmoq, vakillik qilmoq",
        ],
    },
    {
        idAll: 74,
        idMain: 4,
        id: 14,
        english: "positive",
        inenglish: [
            "positive", 
            "patient", 
            "punish", 
            "represent"],
        uzbek: "ijobiy, porloq",
        inuzbek: [
            "ijobiy, porloq",
            "sabrli, toqatli",
            "jazolamoq",
            "vakil bo'lmoq, vakillik qilmoq",
        ],
    },
    {
        idAll: 75,
        idMain: 4,
        id: 15,
        english: "punish",
        inenglish: [
            "punish", 
            "patient", 
            "positive", 
            "represent"],
        uzbek: "jazolamoq",
        inuzbek: [
            "jazolamoq",
            "sabrli, toqatli",
            "ijobiy, porloq",
            "vakil bo'lmoq, vakillik qilmoq",
        ],
    },
    {
        idAll: 76,
        idMain: 4,
        id: 16,
        english: "represent",
        inenglish: [
            "represent",
            "patient", 
            "positive", 
            "punish", 
        ],
        uzbek: "vakil bo'lmoq, vakillik qilmoq",
        inuzbek: [
            "vakil bo'lmoq, vakillik qilmoq",
            "sabrli, toqatli",
            "ijobiy, porloq",
            "jazolamoq",
        ],
    },

    {
        idAll: 77,
        idMain: 4,
        id: 17,
        english: "shake",
        inenglish: [
            "shake", 
            "spread", 
            "stroll", 
            "village"],
        uzbek: "silkitmoq, siltamoq; silkinmoq",
        inuzbek: [
            "silkitmoq, siltamoq; silkinmoq",
            "tarqalmoq; surkamoq, surtmoq",
            "sayr qilmoq, aylanib kelmoq",
            "qishloq, ovul",
        ],
    },
    {
        idAll: 78,
        idMain: 4,
        id: 18,
        english: "spread",
        inenglish: [
            "spread", 
            "shake", 
            "stroll", 
            "village"],
        uzbek: "tarqalmoq; surkamoq, surtmoq",
        inuzbek: [
            "tarqalmoq; surkamoq, surtmoq",
            "silkitmoq, siltamoq; silkinmoq",
            "sayr qilmoq, aylanib kelmoq",
            "qishloq, ovul",
        ],
    },
    {
        idAll: 79,
        idMain: 4,
        id: 19,
        english: "stroll",
        inenglish: [
            "stroll", 
            "shake", 
            "spread", 
            "village"],
        uzbek: "sayr qilmoq, aylanib kelmoq",
        inuzbek: [
            "sayr qilmoq, aylanib kelmoq",
            "silkitmoq, siltamoq; silkinmoq",
            "tarqalmoq; surkamoq, surtmoq",
            "qishloq, ovul",
        ],
    },
    {
        idAll: 80,
        idMain: 4,
        id: 20,
        english: "village",
        inenglish: [
            "village",
            "shake", 
            "spread", 
            "stroll", 
        ],
        uzbek: "qishloq, ovul",
        inuzbek: [
            "qishloq, ovul",
            "silkitmoq, siltamoq; silkinmoq",
            "tarqalmoq; surkamoq, surtmoq",
            "sayr qilmoq, aylanib kelmoq",
        ],
    },

    // UNIT 5
    {
        idAll: 81,
        idMain: 5,
        id: 1,
        english: "aware",
        inenglish: [
            "aware",
            "badly", 
            "belong", 
            "continue", 
        ],
        uzbek: "xabardor, ogoh",
        inuzbek: [
            "xabardor, ogoh",
            "yomon; jiddiy",
            "tegishli bo'lmoq",
            "davom etmoq/ettirmoq",
        ],
    },
    {
        idAll: 82,
        idMain: 5,
        id: 1,
        english: "badly",
        inenglish: [
            "badly", 
            "aware",
            "belong", 
            "continue", 
        ],
        uzbek: "yomon; jiddiy",
        inuzbek: [
            "yomon; jiddiy",
            "xabardor, ogoh",
            "tegishli bo'lmoq",
            "davom etmoq/ettirmoq",
        ],
    },
    {
        idAll: 83,
        idMain: 5,
        id: 1,
        english: "belong",
        inenglish: [
            "belong", 
            "aware",
            "badly", 
            "continue", 
        ],
        uzbek: "tegishli bo'lmoq",
        inuzbek: [
            "tegishli bo'lmoq",
            "xabardor, ogoh",
            "yomon; jiddiy",
            "davom etmoq/ettirmoq",
        ],
    },
    {
        idAll: 84,
        idMain: 5,
        id: 1,
        english: "continue",
        inenglish: [
            "continue", 
            "aware",
            "badly", 
            "belong", 
        ],
        uzbek: "davom etmoq/ettirmoq",
        inuzbek: [
            "davom etmoq/ettirmoq",
            "xabardor, ogoh",
            "yomon; jiddiy",
            "tegishli bo'lmoq",
        ],
    },

    {
        idAll: 85,
        idMain: 5,
        id: 1,
        english: "error",
        inenglish: [
            "error",
            "experience", 
            "field", 
            "hurt", 
        ],
        uzbek: "xato",
        inuzbek: [
            "xato",
            "taassurot, kechinma",
            "keng maydon, dala",
            "jarohatlamoq, jarohat yetkazmoq",
        ],
    },
    {
        idAll: 86,
        idMain: 5,
        id: 1,
        english: "experience",
        inenglish: [
            "experience", 
            "error",
            "field", 
            "hurt", 
        ],
        uzbek: "taassurot, kechinma",
        inuzbek: [
            "taassurot, kechinma",
            "xato",
            "keng maydon, dala",
            "jarohatlamoq, jarohat yetkazmoq",
        ],
    },
    {
        idAll: 87,
        idMain: 5,
        id: 1,
        english: "field",
        inenglish: [
            "field", 
            "error",
            "experience", 
            "hurt", 
        ],
        uzbek: "keng maydon, dala",
        inuzbek: [
            "keng maydon, dala",
            "xato",
            "taassurot, kechinma",
            "jarohatlamoq, jarohat yetkazmoq",
        ],
    },
    {
        idAll: 88,
        idMain: 5,
        id: 1,
        english: "hurt",
        inenglish: [
            "hurt", 
            "error",
            "experience", 
            "field", 
        ],
        uzbek: "jarohatlamoq, jarohat yetkazmoq",
        inuzbek: [
            "jarohatlamoq, jarohat yetkazmoq",
            "xato",
            "taassurot, kechinma",
            "keng maydon, dala",
        ],
    },

    {
        idAll: 89,
        idMain: 5,
        id: 1,
        english: "judgment",
        inenglish: [
            "judgment",
            "likely", 
            "normal", 
            "rare", 
        ],
        uzbek: "qaror qabul qilish; fikr",
        inuzbek: [
            "qaror qabul qilish; fikr",
            "ehtimol, balki, mumkin",
            "odatiy, har doimgi",
            "kamdan-kam; noyob, kamyob",
        ],
    },
    {
        idAll: 90,
        idMain: 5,
        id: 1,
        english: "likely",
        inenglish: [
            "likely", 
            "judgment",
            "normal", 
            "rare", 
        ],
        uzbek: "ehtimol, balki, mumkin",
        inuzbek: [
            "ehtimol, balki, mumkin",
            "qaror qabul qilish; fikr",
            "odatiy, har doimgi",
            "kamdan-kam; noyob, kamyob",
        ],
    },
    {
        idAll: 91,
        idMain: 5,
        id: 1,
        english: "normal",
        inenglish: [
            "normal", 
            "judgment",
            "likely", 
            "rare", 
        ],
        uzbek: "odatiy, har doimgi",
        inuzbek: [
            "odatiy, har doimgi",
            "qaror qabul qilish; fikr",
            "ehtimol, balki, mumkin",
            "kamdan-kam; noyob, kamyob",
        ],
    },
    {
        idAll: 92,
        idMain: 5,
        id: 1,
        english: "rare",
        inenglish: [
            "rare", 
            "judgment",
            "likely", 
            "normal", 
        ],
        uzbek: "kamdan-kam; noyob, kamyob",
        inuzbek: [
            "kamdan-kam; noyob, kamyob",
            "qaror qabul qilish; fikr",
            "ehtimol, balki, mumkin",
            "odatiy, har doimgi",
        ],
    },

    {
        idAll: 93,
        idMain: 5,
        id: 1,
        english: "relax",
        inenglish: [
            "relax",
            "request", 
            "reside", 
            "result", 
        ],
        uzbek: "dam olmoq, hordiq chiqarmoq",
        inuzbek: [
            "dam olmoq, hordiq chiqarmoq",
            "so'ramoq",
            "muayyan yashamoq, istiqomat qilmoq",
            "natija, oqibat",
        ],
    },
    {
        idAll: 94,
        idMain: 5,
        id: 1,
        english: "request",
        inenglish: [
            "request", 
            "relax",
            "reside", 
            "result", 
        ],
        uzbek: "so'ramoq",
        inuzbek: [
            "so'ramoq",
            "dam olmoq, hordiq chiqarmoq",
            "muayyan yashamoq, istiqomat qilmoq",
            "natija, oqibat",
        ],
    },
    {
        idAll: 95,
        idMain: 5,
        id: 1,
        english: "reside",
        inenglish: [
            "reside", 
            "relax",
            "request", 
            "result", 
        ],
        uzbek: "muayyan yashamoq, istiqomat qilmoq",
        inuzbek: [
            "muayyan yashamoq, istiqomat qilmoq",
            "dam olmoq, hordiq chiqarmoq",
            "so'ramoq",
            "natija, oqibat",
        ],
    },
    {
        idAll: 96,
        idMain: 5,
        id: 1,
        english: "result",
        inenglish: [
            "result", 
            "relax",
            "request", 
            "reside", 
        ],
        uzbek: "natija, oqibat",
        inuzbek: [
            "natija, oqibat",
            "dam olmoq, hordiq chiqarmoq",
            "so'ramoq",
            "muayyan yashamoq, istiqomat qilmoq",
        ],
    },

    {
        idAll: 97,
        idMain: 5,
        id: 1,
        english: "roll",
        inenglish: [
            "roll",
            "since", 
            "visible", 
            "wild", 
        ],
        uzbek: "yumalatmoq, dumalatmoq",
        inuzbek: [
            "yumalatmoq, dumalatmoq",
            "-dan beri/buyon",
            "ko'zga ko'rinarli, ko'rinib turgan",
            "yovvoyi",
        ],
    },
    {
        idAll: 98,
        idMain: 5,
        id: 1,
        english: "since",
        inenglish: [
            "since", 
            "roll",
            "visible", 
            "wild", 
        ],
        uzbek: "-dan beri/buyon",
        inuzbek: [
            "-dan beri/buyon",
            "yumalatmoq, dumalatmoq",
            "ko'zga ko'rinarli, ko'rinib turgan",
            "yovvoyi",
        ],
    },
    {
        idAll: 99,
        idMain: 5,
        id: 1,
        english: "visible",
        inenglish: [
            "visible", 
            "roll",
            "since", 
            "wild", 
        ],
        uzbek: "ko'zga ko'rinarli, ko'rinib turgan",
        inuzbek: [
            "ko'zga ko'rinarli, ko'rinib turgan",
            "yumalatmoq, dumalatmoq",
            "-dan beri/buyon",
            "yovvoyi",
        ],
    },
    {
        idAll: 100,
        idMain: 5,
        id: 1,
        english: "wild",
        inenglish: [
            "wild", 
            "roll",
            "since", 
            "visible", 
        ],
        uzbek: "yovvoyi",
        inuzbek: [
            "yovvoyi",
            "yumalatmoq, dumalatmoq",
            "-dan beri/buyon",
            "ko'zga ko'rinarli, ko'rinib turgan",
        ],
    },

    // UNIT 6

    // UNIT 7
];

export const dataStarters = [
    {
        idAll: 1,
        idUnit: 1,
        section: 1,
        id: 1,
        en: "address",
        isen: ["address", "afternoon", "again", "a little"],
        uz: "Manzil",
        isuz: ["Manzil", "Tushgi vaqt, obed", "Yana", "Biroz(kam miqdorda)"],
        img: "",
    },
    {
        idAll: 2,
        idUnit: 1,
        section: 1,
        id: 2,
        en: "afternoon",
        isen: ["afternoon", "address", "again", "a little"],
        uz: "Tushgi vaqt, obed",
        isuz: ["Tushgi vaqt, obed", "Manzil", "Yana", "Biroz(kam miqdorda)"],
        img: "",
    },
    {
        idAll: 3,
        idUnit: 1,
        section: 1,
        id: 3,
        en: "again",
        isen: ["again", "address", "afternoon", "a little"],
        uz: "Yana",
        isuz: ["Yana", "Manzil", "Tushgi vaqt, obed", "Biroz(kam miqdorda)"],
        img: "",
    },
    {
        idAll: 4,
        idUnit: 1,
        section: 1,
        id: 4,
        en: "a little",
        isen: ["a little", "address", "afternoon", "again"],
        uz: "Biroz(kam miqdorda)",
        isuz: ["Biroz(kam miqdorda)", "Manzil", "Tushgi vaqt, obed", "Yana"],
        img: "",
    },
    {
        idAll: 5,
        idUnit: 1,
        section: 1,
        id: 5,
        en: "all over",
        isen: ["all over", "alphabet", "also", "ask"],
        uz: "Hamma joyda",
        isuz: ["Hamma joyda", "Alifbo", "Shuningdek", "So'ramoq"],
        img: "",
    },
    {
        idAll: 6,
        idUnit: 1,
        section: 1,
        id: 6,
        en: "alphabet",
        isen: ["alphabet", "all over", "also", "ask"],
        uz: "Alifbo",
        isuz: ["Alifbo", "Hamma joyda", "Shuningdek", "So'ramoq"],
        img: "",
    },
    {
        idAll: 7,
        idUnit: 1,
        section: 1,
        id: 7,
        en: "also",
        isen: ["also", "all over", "alphabet", "ask"],
        uz: "Shuningdek",
        isuz: ["Shuningdek", "Hamma joyda", "Alifbo", "So'ramoq"],
        img: "",
    },
    {
        idAll: 8,
        idUnit: 1,
        section: 1,
        id: 8,
        en: "ask",
        isen: ["ask", "all over", "alphabet", "also"],
        uz: "So'ramoq",
        isuz: ["So'ramoq", "Hamma joyda", "Alifbo", "Shuningdek"],
        img: "",
    },
    {
        idAll: 9,
        idUnit: 1,
        section: 1,
        id: 9,
        en: "at",
        isen: ["at", "brother", "capital", "car"],
        uz: "Da(predlog)",
        isuz: ["Da(predlog)", "Aka,uka", "Bosh harf", "Mashina"],
        img: "",
    },
    {
        idAll: 10,
        idUnit: 1,
        section: 1,
        id: 10,
        en: "brother",
        isen: ["brother", "at", "capital", "car"],
        uz: "Aka,uka",
        isuz: ["Aka,uka", "Da(predlog)", "Bosh harf", "Mashina"],
        img: "",
    },
    {
        idAll: 11,
        idUnit: 1,
        section: 1,
        id: 11,
        en: "capital",
        isen: ["capital", "at", "brother", "car"],
        uz: "Bosh harf",
        isuz: ["Bosh harf", "Da(predlog)", "Aka,uka", "Mashina"],
        img: "",
    },
    {
        idAll: 12,
        idUnit: 1,
        section: 1,
        id: 12,
        en: "car",
        isen: ["car", "at", "brother", "capital"],
        uz: "Mashina",
        isuz: ["Mashina", "Da(predlog)", "Aka,uka", "Bosh harf"],
        img: "",
    },
    {
        idAll: 13,
        idUnit: 1,
        section: 1,
        id: 13,
        en: "CD",
        isen: ["CD", "class", "come", "concert"],
        uz: "Disk",
        isuz: ["Disk", "Sinf", "Kelmoq", "Konsert"],
        img: "",
    },
    {
        idAll: 14,
        idUnit: 1,
        section: 1,
        id: 14,
        en: "class",
        isen: ["class", "CD", "come", "concert"],
        uz: "Sinf",
        isuz: ["Sinf", "Disk", "Kelmoq", "Konsert"],
        img: "",
    },
    {
        idAll: 15,
        idUnit: 1,
        section: 1,
        id: 15,
        en: "come",
        isen: ["come", "CD", "class", "concert"],
        uz: "Kelmoq",
        isuz: ["Kelmoq", "Disk", "Sinf", "Konsert"],
        img: "",
    },
    {
        idAll: 16,
        idUnit: 1,
        section: 1,
        id: 16,
        en: "concert",
        isen: ["concert", "CD", "class", "come"],
        uz: "Konsert",
        isuz: ["Konsert", "Disk", "Sinf", "Kelmoq"],
        img: "",
    },
    {
        idAll: 17,
        idUnit: 1,
        section: 1,
        id: 17,
        en: "conversation",
        isen: ["conversation", "correct", "credit card", "date of birth"],
        uz: "Suhbat",
        isuz: ["Suhbat", "To'g'ri", "Kredit karta", "Tug'ilgan sana"],
        img: "",
    },
    {
        idAll: 18,
        idUnit: 1,
        section: 1,
        id: 18,
        en: "correct",
        isen: ["correct", "conversation", "credit card", "date of birth"],
        uz: "To'g'ri",
        isuz: ["To'g'ri", "Suhbat", "Kredit karta", "Tug'ilgan sana"],
        img: "",
    },
    {
        idAll: 19,
        idUnit: 1,
        section: 1,
        id: 19,
        en: "credit card",
        isen: ["credit card", "conversation", "correct", "date of birth"],
        uz: "Kredit karta",
        isuz: ["Kredit karta", "Suhbat", "To'g'ri", "Tug'ilgan sana"],
        img: "",
    },
    {
        idAll: 20,
        idUnit: 1,
        section: 1,
        id: 20,
        en: "date of birth",
        isen: ["date of birth", "conversation", "correct", "credit card"],
        uz: "Tug'ilgan sana",
        isuz: ["Tug'ilgan sana", "Suhbat", "To'g'ri", "Kredit karta"],
        img: "",
    },
    {
        idAll: 21,
        idUnit: 1,
        section: 2,
        id: 21,
        en: "day",
        isen: ["day", "dictionary", "different", "do"],
        uz: "Kun",
        isuz: ["Kun", "Lug'at", "Farq qilmoq", "Qilmoq,bajarmoq"],
        img: "",
    },
    {
        idAll: 22,
        idUnit: 1,
        section: 2,
        id: 22,
        en: "dictionary",
        isen: ["dictionary", "day", "different", "do"],
        uz: "Lug'at",
        isuz: ["Lug'at", "Kun", "Farq qilmoq", "Qilmoq,bajarmoq"],
        img: "",
    },
    {
        idAll: 23,
        idUnit: 1,
        section: 2,
        id: 23,
        en: "different",
        isen: ["different", "day", "dictionary", "do"],
        uz: "Farq qilmoq",
        isuz: ["Farq qilmoq", "Kun", "Lug'at", "Qilmoq,bajarmoq"],
        img: "",
    },
    {
        idAll: 24,
        idUnit: 1,
        section: 2,
        id: 24,
        en: "do",
        isen: ["do", "day", "dictionary", "different"],
        uz: "Qilmoq,bajarmoq",
        isuz: ["Qilmoq,bajarmoq", "Kun", "Lug'at", "Farq qilmoq"],
        img: "",
    },
    {
        idAll: 25,
        idUnit: 1,
        section: 2,
        id: 25,
        en: "double",
        isen: ["double", "eight", "email address", "English"],
        uz: "Ikki barobar",
        isuz: [
            "Ikki barobar",
            "Sakkiz",
            "Electron pochta manzili",
            "Ingliz tili",
        ],
        img: "",
    },
    {
        idAll: 26,
        idUnit: 1,
        section: 2,
        id: 26,
        en: "eight",
        isen: ["eight", "double", "email address", "English"],
        uz: "Sakkiz",
        isuz: [
            "Sakkiz",
            "Ikki barobar",
            "Electron pochta manzili",
            "Ingliz tili",
        ],
        img: "",
    },
    {
        idAll: 27,
        idUnit: 1,
        section: 2,
        id: 27,
        en: "email address",
        isen: ["email address", "double", "eight", "English"],
        uz: "Electron pochta manzili",
        isuz: [
            "Electron pochta manzili",
            "Ikki barobar",
            "Sakkiz",
            "Ingliz tili",
        ],
        img: "",
    },
    {
        idAll: 28,
        idUnit: 1,
        section: 2,
        id: 28,
        en: "English",
        isen: ["English", "double", "eight", "email address"],
        uz: "Ingliz tili",
        isuz: [
            "Ingliz tili",
            "Ikki barobar",
            "Sakkiz",
            "Electron pochta manzili",
        ],
        img: "",
    },
    {
        idAll: 29,
        idUnit: 1,
        section: 2,
        id: 29,
        en: "evening",
        isen: ["evening", "every", "everyone", "everything"],
        uz: "Kechqurun",
        isuz: ["Kechqurun", "Har bir", "Hamma", "Hamma narsa"],
        img: "",
    },
    {
        idAll: 30,
        idUnit: 1,
        section: 2,
        id: 30,
        en: "every",
        isen: ["every", "evening", "everyone", "everything"],
        uz: "Har bir",
        isuz: ["Har bir", "Kechqurun", "Hamma", "Hamma narsa"],
        img: "",
    },
    {
        idAll: 31,
        idUnit: 1,
        section: 2,
        id: 31,
        en: "everyone",
        isen: ["everyone", "evening", "every", "everything"],
        uz: "Hamma",
        isuz: ["Hamma", "Kechqurun", "Har bir", "Hamma narsa"],
        img: "",
    },
    {
        idAll: 32,
        idUnit: 1,
        section: 2,
        id: 32,
        en: "everything",
        isen: ["everything", "evening", "every", "everyone"],
        uz: "Hamma narsa",
        isuz: ["Hamma narsa", "Kechqurun", "Har bir", "Hamma"],
        img: "",
    },
    {
        idAll: 33,
        idUnit: 1,
        section: 2,
        id: 33,
        en: "exercise",
        isen: ["exercise", "favourite", "finish", "first"],
        uz: "Topshiriq",
        isuz: ["Topshiriq", "Sevimli", "Tugatmoq", "Birinchi"],
        img: "",
    },
    {
        idAll: 34,
        idUnit: 1,
        section: 2,
        id: 34,
        en: "favourite",
        isen: ["favourite", "exercise", "finish", "first"],
        uz: "Sevimli",
        isuz: ["Sevimli", "Topshiriq", "Tugatmoq", "Birinchi"],
        img: "",
    },
    {
        idAll: 35,
        idUnit: 1,
        section: 2,
        id: 35,
        en: "finish",
        isen: ["finish", "exercise", "favourite", "first"],
        uz: "Tugatmoq",
        isuz: ["Tugatmoq", "Topshiriq", "Sevimli", "Birinchi"],
        img: "",
    },
    {
        idAll: 36,
        idUnit: 1,
        section: 2,
        id: 36,
        en: "first",
        isen: ["first", "exercise", "favourite", "finish"],
        uz: "Birinchi",
        isuz: ["Birinchi", "Topshiriq", "Sevimli", "Tugatmoq"],
        img: "",
    },
    {
        idAll: 37,
        idUnit: 1,
        section: 2,
        id: 37,
        en: "first name",
        isen: ["first name", "five", "for example", "four"],
        uz: "Ism",
        isuz: ["Ism", "Besh", "Masalan", "To’rt"],
        img: "",
    },
    {
        idAll: 38,
        idUnit: 1,
        section: 2,
        id: 38,
        en: "five",
        isen: ["five", "first name", "for example", "four"],
        uz: "Besh",
        isuz: ["Besh", "Ism", "Masalan", "To’rt"],
        img: "",
    },
    {
        idAll: 39,
        idUnit: 1,
        section: 2,
        id: 39,
        en: "for example",
        isen: ["for example", "first name", "five", "four"],
        uz: "Masalan",
        isuz: ["Masalan", "Ism", "Besh", "To’rt"],
        img: "",
    },
    {
        idAll: 40,
        idUnit: 1,
        section: 2,
        id: 40,
        en: "four",
        isen: ["four", "first name", "five", "for example"],
        uz: "To’rt",
        isuz: ["To’rt", "Ism", "Besh", "Masalan"],
        img: "",
    },
    {
        idAll: 41,
        idUnit: 1,
        id: 41,
        en: "friend",
        isen: ["friend", "from", "goal", "great"],
        uz: "Do’st",
        isuz: ["Do’st", "Dan(predlog)", "Maqsad", "Ajoyib"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 42,
        idUnit: 1,
        id: 42,
        en: "from",
        isen: ["from", "friend", "goal", "great"],
        uz: "Dan(predlog)",
        isuz: ["Dan(predlog)", "Do’st", "Maqsad", "Ajoyib"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 43,
        idUnit: 1,
        id: 43,
        en: "goal",
        isen: ["goal", "friend", "from", "great"],
        uz: "Maqsad",
        isuz: ["Maqsad", "Do’st", "Dan(predlog)", "Ajoyib"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 44,
        idUnit: 1,
        id: 44,
        en: "great",
        isen: ["great", "friend", "from", "goal"],
        uz: "Ajoyib",
        isuz: ["Ajoyib", "Do’st", "Dan(predlog)", "Maqsad"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 45,
        idUnit: 1,
        id: 45,
        en: "have",
        isen: ["have", "he", "hear", "help"],
        uz: "Bor",
        isuz: ["Bor", "U(erkak kishiga nisbatan)", "Eshitmoq", "Yordam bermoq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 46,
        idUnit: 1,
        id: 46,
        en: "he",
        isen: ["he", "have", "hear", "help"],
        uz: "U(erkak kishiga nisbatan)",
        isuz: ["U(erkak kishiga nisbatan)", "Bor", "Eshitmoq", "Yordam bermoq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 47,
        idUnit: 1,
        id: 47,
        en: "hear",
        isen: ["hear", "have", "he", "help"],
        uz: "Eshitmoq",
        isuz: ["Eshitmoq", "Bor", "U(erkak kishiga nisbatan)", "Yordam bermoq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 48,
        idUnit: 1,
        id: 48,
        en: "help",
        isen: ["help", "have", "he", "hear"],
        uz: "Yordam bermoq",
        isuz: ["Yordam bermoq", "Bor", "U(erkak kishiga nisbatan)", "Eshitmoq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 49,
        idUnit: 1,
        id: 49,
        en: "her",
        isen: ["her", "here", "high", "his"],
        uz: "Uning(ayol kishiga nisbatan)",
        isuz: [
            "Uning(ayol kishiga nisbatan)",
            "Shu yerda",
            "Baland",
            "Uning(erkak kishiga nisbatan)",
        ],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 50,
        idUnit: 1,
        id: 50,
        en: "here",
        isen: ["here", "her", "high", "his"],
        uz: "Shu yerda",
        isuz: [
            "Shu yerda",
            "Uning(ayol kishiga nisbatan)",
            "Baland",
            "Uning(erkak kishiga nisbatan)",
        ],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 51,
        idUnit: 1,
        id: 51,
        en: "high",
        isen: ["high", "her", "here", "his"],
        uz: "Baland",
        isuz: [
            "Baland",
            "Uning(ayol kishiga nisbatan)",
            "Shu yerda",
            "Uning(erkak kishiga nisbatan)",
        ],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 52,
        idUnit: 1,
        id: 52,
        en: "his",
        isen: ["his", "her", "here", "high"],
        uz: "Uning(erkak kishiga nisbatan)",
        isuz: [
            "Uning(erkak kishiga nisbatan)",
            "Uning(ayol kishiga nisbatan)",
            "Shu yerda",
            "Baland",
        ],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 53,
        idUnit: 1,
        id: 53,
        en: "home",
        isen: ["home", "home number", "how", "ID number"],
        uz: "Uy",
        isuz: ["Uy", "Uy raqami", "Qanday", "ID raqami"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 54,
        idUnit: 1,
        id: 54,
        en: "home number",
        isen: ["home number", "home", "how", "ID number"],
        uz: "Uy raqami",
        isuz: ["Uy raqami", "Uy", "Qanday", "ID raqami"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 55,
        idUnit: 1,
        id: 55,
        en: "how",
        isen: ["how", "home", "home number", "ID number"],
        uz: "Qanday",
        isuz: ["Qanday", "Uy", "Uy raqami", "ID raqami"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 56,
        idUnit: 1,
        id: 56,
        en: "ID number",
        isen: ["ID number", "home", "home number", "how"],
        uz: "ID raqami",
        isuz: ["ID raqami", "Uy", "Uy raqami", "Qanday"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 57,
        idUnit: 1,
        id: 57,
        en: "initial",
        isen: ["initial", "intonation", "introduce", "introduction"],
        uz: "Tashabbus",
        isuz: ["Tashabbus", "Intonatsiya", "Tanishtirmoq", "Tanishtiruv"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 58,
        idUnit: 1,
        id: 58,
        en: "intonation",
        isen: ["intonation", "initial", "introduce", "introduction"],
        uz: "Intonatsiya",
        isuz: ["Intonatsiya", "Tashabbus", "Tanishtirmoq", "Tanishtiruv"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 59,
        idUnit: 1,
        id: 59,
        en: "introduce",
        isen: ["introduce", "initial", "intonation", "introduction"],
        uz: "Tanishtirmoq",
        isuz: ["Tanishtirmoq", "Tashabbus", "Intonatsiya", "Tanishtiruv"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 60,
        idUnit: 1,
        id: 60,
        en: "introduction",
        isen: ["introduction", "initial", "intonation", "introduce"],
        uz: "Tanishtiruv",
        isuz: ["Tanishtiruv", "Tashabbus", "Intonatsiya", "Tanishtirmoq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 61,
        idUnit: 1,
        id: 61,
        en: "last name",
        isen: ["last name", "like", "listen", "long"],
        uz: "Familiya",
        isuz: ["Familiya", "O’xshamoq", "Tinglamoq", "Uzun"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 62,
        idUnit: 1,
        id: 62,
        en: "like",
        isen: ["like", "last name", "listen", "long"],
        uz: "O’xshamoq",
        isuz: ["O’xshamoq", "Familiya", "Tinglamoq", "Uzun"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 63,
        idUnit: 1,
        id: 63,
        en: "listen",
        isen: ["listen", "last name", "like", "long"],
        uz: "Tinglamoq",
        isuz: ["Tinglamoq", "Familiya", "O’xshamoq", "Uzun"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 64,
        idUnit: 1,
        id: 64,
        en: "long",
        isen: ["long", "last name", "like", "listen"],
        uz: "Uzun",
        isuz: ["Uzun", "Familiya", "O’xshamoq", "Tinglamoq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 65,
        idUnit: 1,
        id: 65,
        en: "loud",
        isen: ["loud", "meet", "middle name", "morning"],
        uz: "Baland ovoz",
        isuz: ["Baland ovoz", "Uchrashmoq", "Otasining ismi", "Tong"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 66,
        idUnit: 1,
        id: 66,
        en: "meet",
        isen: ["meet", "loud", "middle name", "morning"],
        uz: "Uchrashmoq",
        isuz: ["Uchrashmoq", "Baland ovoz", "Otasining ismi", "Tong"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 67,
        idUnit: 1,
        id: 67,
        en: "middle name",
        isen: ["middle name", "loud", "meet", "morning"],
        uz: "Otasining ismi",
        isuz: ["Otasining ismi", "Baland ovoz", "Uchrashmoq", "Tong"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 68,
        idUnit: 1,
        id: 68,
        en: "morning",
        isen: ["morning", "loud", "meet", "middle name"],
        uz: "Tong",
        isuz: ["Tong", "Baland ovoz", "Uchrashmoq", "Otasining ismi"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 69,
        idUnit: 1,
        id: 69,
        en: "my",
        isen: ["my", "name", "new", "nice"],
        uz: "Mening",
        isuz: ["Mening", "Ism", "Yangi", "Yoqimli"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 70,
        idUnit: 1,
        id: 70,
        en: "name",
        isen: ["name", "my", "new", "nice"],
        uz: "Ism",
        isuz: ["Ism", "Mening", "Yangi", "Yoqimli"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 71,
        idUnit: 1,
        id: 71,
        en: "new",
        isen: ["new", "my", "name", "nice"],
        uz: "Yangi",
        isuz: ["Yangi", "Mening", "Ism", "Yoqimli"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 72,
        idUnit: 1,
        id: 72,
        en: "nice",
        isen: ["nice", "my", "name", "new"],
        uz: "Yoqimli",
        isuz: ["Yoqimli", "Mening", "Ism", "Yangi"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 73,
        idUnit: 1,
        id: 73,
        en: "nickname",
        isen: ["nickname", "night", "nine", "now"],
        uz: "Taxallus",
        isuz: ["Taxallus", "Kechasi", "To’qqiz", "Hozir"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 74,
        idUnit: 1,
        id: 74,
        en: "night",
        isen: ["night", "nickname", "nine", "now"],
        uz: "Kechasi",
        isuz: ["Kechasi", "Taxallus", "To’qqiz", "Hozir"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 75,
        idUnit: 1,
        id: 75,
        en: "nine",
        isen: ["nine", "nickname", "night", "now"],
        uz: "To’qqiz",
        isuz: ["To’qqiz", "Taxallus", "Kechasi", "Hozir"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 76,
        idUnit: 1,
        id: 76,
        en: "now",
        isen: ["now", "nickname", "night", "nine"],
        uz: "Hozir",
        isuz: ["Hozir", "Taxallus", "Kechasi", "To’qqiz"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 77,
        idUnit: 1,
        id: 77,
        en: "number",
        isen: ["number", "office", "one", "online"],
        uz: "Raqam",
        isuz: ["Raqam", "Ofis", "Bir", "Onlayn"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 78,
        idUnit: 1,
        id: 78,
        en: "office",
        isen: ["office", "number", "one", "online"],
        uz: "Ofis",
        isuz: ["Ofis", "Raqam", "Bir", "Onlayn"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 79,
        idUnit: 1,
        id: 79,
        en: "one",
        isen: ["one", "number", "office", "online"],
        uz: "Bir",
        isuz: ["Bir", "Raqam", "Ofis", "Onlayn"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 80,
        idUnit: 1,
        id: 80,
        en: "online",
        isen: ["online", "number", "office", "one"],
        uz: "Onlayn",
        isuz: ["Onlayn", "Raqam", "Ofis", "Bir"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 81,
        idUnit: 1,
        id: 81,
        en: "other",
        isen: ["other", "our", "partner", "people"],
        uz: "Boshqa",
        isuz: ["Boshqa", "Bizning", "Sherik", "Odamlar"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 82,
        idUnit: 1,
        id: 82,
        en: "our",
        isen: ["our", "other", "partner", "people"],
        uz: "Bizning",
        isuz: ["Bizning", "Boshqa", "Sherik", "Odamlar"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 83,
        idUnit: 1,
        id: 83,
        en: "partner",
        isen: ["partner", "other", "our", "people"],
        uz: "Sherik",
        isuz: ["Sherik", "Boshqa", "Bizning", "Odamlar"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 84,
        idUnit: 1,
        id: 84,
        en: "people",
        isen: ["people", "other", "our", "partner"],
        uz: "Odamlar",
        isuz: ["Odamlar", "Boshqa", "Bizning", "Sherik"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 85,
        idUnit: 1,
        id: 85,
        en: "personal information",
        isen: ["personal information", "phone number", "phonetic", "practise"],
        uz: "Shaxsiy ma’lumot",
        isuz: [
            "Shaxsiy ma’lumot",
            "Telefon raqam",
            "Fonetika",
            "Amaliyot o’tamoq",
        ],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 86,
        idUnit: 1,
        id: 86,
        en: "phone number",
        isen: ["phone number", "personal information", "phonetic", "practise"],
        uz: "Telefon raqam",
        isuz: [
            "Telefon raqam",
            "Shaxsiy ma’lumot",
            "Fonetika",
            "Amaliyot o’tamoq",
        ],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 87,
        idUnit: 1,
        id: 87,
        en: "phonetic",
        isen: ["phonetic", "personal information", "phone number", "practise"],
        uz: "Fonetika",
        isuz: [
            "Fonetika",
            "Shaxsiy ma’lumot",
            "Telefon raqam",
            "Amaliyot o’tamoq",
        ],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 88,
        idUnit: 1,
        id: 88,
        en: "practise",
        isen: ["practise", "personal information", "phone number", "phonetic"],
        uz: "Amaliyot o’tamoq",
        isuz: [
            "Amaliyot o’tamoq",
            "Shaxsiy ma’lumot",
            "Telefon raqam",
            "Fonetika",
        ],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 89,
        idUnit: 1,
        id: 89,
        en: "professor",
        isen: ["professor", "pronounce", "pronunciation", "question"],
        uz: "Professor",
        isuz: ["Professor", "Talaffuz qilmoq", "Tallafuz", "Savol"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 90,
        idUnit: 1,
        id: 90,
        en: "pronounce",
        isen: ["pronounce", "professor", "pronunciation", "question"],
        uz: "Talaffuz qilmoq",
        isuz: ["Talaffuz qilmoq", "Professor", "Tallafuz", "Savol"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 91,
        idUnit: 1,
        id: 91,
        en: "pronunciation",
        isen: ["pronunciation", "professor", "pronounce", "question"],
        uz: "Tallafuz",
        isuz: ["Tallafuz", "Professor", "Talaffuz qilmoq", "Savol"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 92,
        idUnit: 1,
        id: 92,
        en: "question",
        isen: ["question", "professor", "pronounce", "pronunciation"],
        uz: "Savol",
        isuz: ["Savol", "Professor", "Talaffuz qilmoq", "Tallafuz"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 93,
        idUnit: 1,
        id: 93,
        en: "real",
        isen: ["real", "repeat", "say", "school"],
        uz: "Haqiqiy",
        isuz: ["Haqiqiy", "Takrorlamoq", "Aytmoq", "Maktab"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 94,
        idUnit: 1,
        id: 94,
        en: "repeat",
        isen: ["repeat", "real", "say", "school"],
        uz: "Takrorlamoq",
        isuz: ["Takrorlamoq", "Haqiqiy", "Aytmoq", "Maktab"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 95,
        idUnit: 1,
        id: 95,
        en: "say",
        isen: ["say", "real", "repeat", "school"],
        uz: "Aytmoq",
        isuz: ["Aytmoq", "Haqiqiy", "Takrorlamoq", "Maktab"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 96,
        idUnit: 1,
        id: 96,
        en: "school",
        isen: ["school", "real", "repeat", "say"],
        uz: "Maktab",
        isuz: ["Maktab", "Haqiqiy", "Takrorlamoq", "Aytmoq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 97,
        idUnit: 1,
        id: 97,
        en: "set",
        isen: ["set", "seven", "show", "sing"],
        uz: "Sozlamoq",
        isuz: ["Sozlamoq", "Yetti", "Ko’rsatuv", "Kuylamoq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 98,
        idUnit: 1,
        id: 98,
        en: "seven",
        isen: ["seven", "set", "show", "sing"],
        uz: "Yetti",
        isuz: ["Yetti", "Sozlamoq", "Ko’rsatuv", "Kuylamoq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 99,
        idUnit: 1,
        id: 99,
        en: "show",
        isen: ["show", "set", "seven", "sing"],
        uz: "Ko’rsatuv",
        isuz: ["Ko’rsatuv", "Sozlamoq", "Yetti", "Kuylamoq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 100,
        idUnit: 1,
        id: 100,
        en: "sing",
        isen: ["sing", "set", "seven", "show"],
        uz: "Kuylamoq",
        isuz: ["Kuylamoq", "Sozlamoq", "Yetti", "Ko’rsatuv"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 101,
        idUnit: 1,
        id: 101,
        en: "singer",
        isen: ["singer", "six", "song", "Spain"],
        uz: "Honanda",
        isuz: ["Honanda", "Olti", "Qo’shiq", "Ispaniya"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 102,
        idUnit: 1,
        id: 102,
        en: "six",
        isen: ["six", "singer", "song", "Spain"],
        uz: "Olti",
        isuz: ["Olti", "Honanda", "Qo’shiq", "Ispaniya"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 103,
        idUnit: 1,
        id: 103,
        en: "song",
        isen: ["song", "singer", "six", "Spain"],
        uz: "Qo’shiq",
        isuz: ["Qo’shiq", "Honanda", "Olti", "Ispaniya"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 104,
        idUnit: 1,
        id: 104,
        en: "Spain",
        isen: ["Spain", "singer", "six", "song"],
        uz: "Ispaniya",
        isuz: ["Ispaniya", "Honanda", "Olti", "Qo’shiq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 105,
        idUnit: 1,
        id: 105,
        en: "speak",
        isen: ["speak", "speaker", "spell", "stressed"],
        uz: "Gapirmoq",
        isuz: ["Gapirmoq", "Ma’ruzachi", "Harflab aytmoq", "Urg’u bermoq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 106,
        idUnit: 1,
        id: 106,
        en: "speaker",
        isen: ["speaker", "speak", "spell", "stressed"],
        uz: "Ma’ruzachi",
        isuz: ["Ma’ruzachi", "Gapirmoq", "Harflab aytmoq", "Urg’u bermoq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 107,
        idUnit: 1,
        id: 107,
        en: "spell",
        isen: ["spell", "speak", "speaker", "stressed"],
        uz: "Harflab aytmoq",
        isuz: ["Harflab aytmoq", "Gapirmoq", "Ma’ruzachi", "Urg’u bermoq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 108,
        idUnit: 1,
        id: 108,
        en: "stressed",
        isen: ["stressed", "speak", "speaker", "spell"],
        uz: "Urg’u bermoq",
        isuz: ["Urg’u bermoq", "Gapirmoq", "Ma’ruzachi", "Harflab aytmoq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 109,
        idUnit: 1,
        id: 109,
        en: "student",
        isen: ["student", "surname", "syllable", "teacher"],
        uz: "Talaba",
        isuz: ["Talaba", "Familiya", "Bo’g’in", "Ustoz"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 110,
        idUnit: 1,
        id: 110,
        en: "surname",
        isen: ["surname", "student", "syllable", "teacher"],
        uz: "Familiya",
        isuz: ["Familiya", "Talaba", "Bo’g’in", "Ustoz"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 111,
        idUnit: 1,
        id: 111,
        en: "syllable",
        isen: ["syllable", "student", "surname", "teacher"],
        uz: "Bo’g’in",
        isuz: ["Bo’g’in", "Talaba", "Familiya", "Ustoz"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 112,
        idUnit: 1,
        id: 112,
        en: "teacher",
        isen: ["teacher", "student", "surname", "syllable"],
        uz: "Ustoz",
        isuz: ["Ustoz", "Talaba", "Familiya", "Bo’g’in"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 113,
        idUnit: 1,
        id: 113,
        en: "ten",
        isen: ["ten", "then", "three", "tick"],
        uz: "O’n",
        isuz: ["O’n", "Keyin", "Uch", "Belgilamoq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 114,
        idUnit: 1,
        id: 114,
        en: "then",
        isen: ["then", "ten", "three", "tick"],
        uz: "Keyin",
        isuz: ["Keyin", "O’n", "Uch", "Belgilamoq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 115,
        idUnit: 1,
        id: 115,
        en: "three",
        isen: ["three", "ten", "then", "tick"],
        uz: "Uch",
        isuz: ["Uch", "O’n", "Keyin", "Belgilamoq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 116,
        idUnit: 1,
        id: 116,
        en: "tick",
        isen: ["tick", "ten", "then", "three"],
        uz: "Belgilamoq",
        isuz: ["Belgilamoq", "O’n", "Keyin", "Uch"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 117,
        idUnit: 1,
        id: 117,
        en: "ticket",
        isen: ["ticket", "transcription", "try", "two"],
        uz: "Bilet",
        isuz: ["Bilet", "Transkripsiya", "Harakat qilib ko’rmoq", "Ikki"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 118,
        idUnit: 1,
        id: 118,
        en: "transcription",
        isen: ["transcription", "ticket", "try", "two"],
        uz: "Transkripsiya",
        isuz: ["Transkripsiya", "Bilet", "Harakat qilib ko’rmoq", "Ikki"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 119,
        idUnit: 1,
        id: 119,
        en: "try",
        isen: ["try", "ticket", "transcription", "two"],
        uz: "Harakat qilib ko’rmoq",
        isuz: ["Harakat qilib ko’rmoq", "Bilet", "Transkripsiya", "Ikki"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 120,
        idUnit: 1,
        id: 120,
        en: "two",
        isen: ["two", "ticket", "transcription", "try"],
        uz: "Ikki",
        isuz: ["Ikki", "Bilet", "Transkripsiya", "Harakat qilib ko’rmoq"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 121,
        idUnit: 1,
        id: 121,
        en: "the United Kingdom",
        isen: ["the United Kingdom", "university", "use", "way"],
        uz: "Savol",
        isuz: ["Birlashga Qirollik", "Universitet", "Foydalanish", "Yo’l"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 122,
        idUnit: 1,
        id: 122,
        en: "university",
        isen: ["university", "the United Kingdom", "use", "way"],
        uz: "Universitet",
        isuz: ["Universitet", "Birlashga Qirollik", "Foydalanish", "Yo’l"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 123,
        idUnit: 1,
        id: 123,
        en: "use",
        isen: ["use", "the United Kingdom", "university", "way"],
        uz: "Foydalanish",
        isuz: ["Foydalanish", "Birlashga Qirollik", "Universitet", "Yo’l"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 124,
        idUnit: 1,
        id: 124,
        en: "way",
        isen: ["way", "the United Kingdom", "university", "use"],
        uz: "Yo’l",
        isuz: ["Yo’l", "Birlashga Qirollik", "Universitet", "Foydalanish"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 125,
        idUnit: 1,
        id: 125,
        en: "website",
        isen: ["website", "what", "which", "with"],
        uz: "Veb-sayt",
        isuz: ["Veb-sayt", "Nima", "Qaysi", "Bilan"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 126,
        idUnit: 1,
        id: 126,
        en: "what",
        isen: ["what", "website", "which", "with"],
        uz: "Nima",
        isuz: ["Nima", "Veb-sayt", "Qaysi", "Bilan"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 127,
        idUnit: 1,
        id: 127,
        en: "which",
        isen: ["which", "website", "what", "with"],
        uz: "Qaysi",
        isuz: ["Qaysi", "Veb-sayt", "Nima", "Bilan"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 128,
        idUnit: 1,
        id: 128,
        en: "with",
        isen: ["with", "website", "what", "which"],
        uz: "Bilan",
        isuz: ["Bilan", "Veb-sayt", "Nima", "Qaysi"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 129,
        idUnit: 1,
        id: 129,
        en: "work",
        isen: ["work", "world", "your", "zero"],
        uz: "Ishlamoq",
        isuz: ["Ishlamoq", "Dunyo", "Sening", "Nol"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 130,
        idUnit: 1,
        id: 130,
        en: "world",
        isen: ["world", "work", "your", "zero"],
        uz: "Dunyo",
        isuz: ["Dunyo", "Ishlamoq", "Sening", "Nol"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 131,
        idUnit: 1,
        id: 131,
        en: "your",
        isen: ["your", "work", "world", "zero"],
        uz: "Sening",
        isuz: ["Sening", "Ishlamoq", "Dunyo", "Nol"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
    {
        idAll: 132,
        idUnit: 1,
        id: 132,
        en: "zero",
        isen: ["zero", "work", "world", "your"],
        uz: "Nol",
        isuz: ["Nol", "Ishlamoq", "Dunyo", "Sening"],
        phonetic: "/fɜː(r)st/",
        partofspeech: "adverb",
        img: "",
    },
]

export const dataElementary = []
